{% set name = "pdf2image" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 787f6dd77dc02786913fd4ee5766bb9241fe807e3c6ee90e3cff18bcf2f23555

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv "

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - pillow

test:
  imports:
    - pdf2image

about:
  home: https://github.com/Belval/pdf2image
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'A wrapper around the pdftoppm and pdftocairo command line tools to convert PDF to a PIL Image list.'

extra:
  recipe-maintainers:
    - benhuff
    - oblute
    - rluria14
