{% set name = "pdf2image" %}
{% set version = "1.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eaa959bc116b420dd7ec415fcae49b98100dda3dd18cd2fdfa86d09f112f6d57

build:
  number: 0
  skip: True    # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - pillow
    - poppler

test:
  imports:
    - pdf2image
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Belval/pdf2image
  doc_url: https://belval.github.io/pdf2image
  dev_url: https://github.com/Belval/pdf2image
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A python module that wraps pdftoppm and pdftocairo to convert PDF to a PIL Image object
  description: A python module that wraps pdftoppm and pdftocairo to convert PDF to a PIL Image object
  

extra:
  recipe-maintainers:
    - mxr-conda
    - benhuff
    - oblute
    - rluria14
