{% set name = "pdf2image" %}
{% set version = "1.16.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 788db5a2d3479aa1ed0ff53c8a52fabfe51aff6eb2be7b8bffbf4c1bedcb3547

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - pillow

test:
  imports:
    - pdf2image

about:
  home: https://github.com/Belval/pdf2image
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A wrapper around the pdftoppm and pdftocairo command line tools to convert PDF to a PIL Image list.

extra:
  recipe-maintainers:
    - mxr-conda
    - benhuff
    - oblute
    - rluria14
